In [34]:
import pandas as pd

# Charger la feuille 2018 du classeur impots

feuille = '2018'
df = pd.read_excel('C:/Users/ketre/Desktop/Projet-Power BI/impots.xlsx', sheet_name=feuille, header=7)

# Afficher les premières lignes du DataFrame pour vérifier le chargement
print(df.head())

   Unnamed: 0  Numéro                   Nom  Année de revenus  \
0         NaN     130      BOUCHES-DU-RHONE              2018
1         NaN     160              CHARENTE              2018
2         NaN     500                MANCHE              2018
3         NaN     620         PAS-DE-CALAIS              2018
4         NaN     640  PYRENEES-ATLANTIQUES              2018

   Nombre de foyers fiscaux  Revenu fiscal de référence  \
0                   1210444                3.238143e+10
1                    210898                4.982192e+09
2                    287724                7.137787e+09
3                    815450                1.837626e+10
4                    405460                1.106038e+10

   Impôt net (total avant CIMR)*  Impôt net (total après CIMR)**        CIMR  \
0                     2448546251                      -113458263  2562004514
1                      255676113                       -31187123   286863236
2                      334468999                       -67753018   402222017
3                      888961536                      -114784628  1003746164
4                      690276072                       -57891989   748168061

   Nombre de foyers fiscaux.1  Revenu fiscal de référence.1  \
0                      612747                  2.527904e+10
1                       99774                  3.525331e+09
2                      142333                  5.024140e+09
3                      339660                  1.221662e+10
4                      212853                  8.379095e+09

   Nombre de foyers concernés       Montant  Nombre de foyers concernés.1  \
0                      769341  2.220055e+10                        415743
1                      123702  3.120986e+09                         87791
2                      169735  4.478198e+09                        124431
3                      506283  1.291748e+10                        296074
4                      246043  6.811603e+09                        162427

    Montant.1
0  9355656381
1  1879799953
2  2712404315
3  6089623578
4  3851462320

In [35]:
# Supprimer les colonnes où toutes les valeurs sont NaN
df_sans_nans_all = df.dropna(axis=1, how='all')

# Afficher le DataFrame après suppression des colonnes où toutes les valeurs sont NaN
print(df_sans_nans_all.head())

   Numéro                   Nom  Année de revenus  Nombre de foyers fiscaux  \
0     130      BOUCHES-DU-RHONE              2018                   1210444
1     160              CHARENTE              2018                    210898
2     500                MANCHE              2018                    287724
3     620         PAS-DE-CALAIS              2018                    815450
4     640  PYRENEES-ATLANTIQUES              2018                    405460

   Revenu fiscal de référence  Impôt net (total avant CIMR)*  \
0                3.238143e+10                     2448546251
1                4.982192e+09                      255676113
2                7.137787e+09                      334468999
3                1.837626e+10                      888961536
4                1.106038e+10                      690276072

   Impôt net (total après CIMR)**        CIMR  Nombre de foyers fiscaux.1  \
0                      -113458263  2562004514                      612747
1                       -31187123   286863236                       99774
2                       -67753018   402222017                      142333
3                      -114784628  1003746164                      339660
4                       -57891989   748168061                      212853

   Revenu fiscal de référence.1  Nombre de foyers concernés       Montant  \
0                  2.527904e+10                      769341  2.220055e+10
1                  3.525331e+09                      123702  3.120986e+09
2                  5.024140e+09                      169735  4.478198e+09
3                  1.221662e+10                      506283  1.291748e+10
4                  8.379095e+09                      246043  6.811603e+09

   Nombre de foyers concernés.1   Montant.1
0                        415743  9355656381
1                         87791  1879799953
2                        124431  2712404315
3                        296074  6089623578
4                        162427  3851462320

In [78]:
import pandas as pd

# Charger la feuille 1984_1999 du classeur impots

feuille = '1984_1999'
df = pd.read_excel('C:/Users/ketre/Desktop/Projet-Power BI/impots.xlsx', sheet_name=feuille, header=7)

# Afficher les premières lignes du DataFrame pour vérifier le chargement
print(df.head())

   Unnamed: 0 Numéro                      Nom  Année de revenus  \
0         NaN    010                      Ain              1984
1         NaN    020                    Aisne              1984
2         NaN    030                   Allier              1984
3         NaN    040  Alpes-de-Haute-Provence              1984
4         NaN    050             Hautes-Alpes              1984

   Nombre de foyers fiscaux  Revenus nets imposables     Impôt net  \
0                    181534             1.737362e+09  1.932327e+08
1                    235174             2.077326e+09  2.257485e+08
2                    173330             1.432056e+09  1.464150e+08
3                     55860             4.936463e+08  5.418975e+07
4                     49883             4.335536e+08  4.762610e+07

   Nombre de foyers fiscaux.1  Revenus nets imposables.1  \
0                      113754               1.475392e+09
1                      134875               1.703993e+09
2                       95784               1.171677e+09
3                       32392               4.164714e+08
4                       28496               3.637526e+08

   Nombre de foyers fiscaux.2  Revenus nets imposables.2
0                       67780               2.619703e+08
1                      100299               3.733335e+08
2                       77546               2.603782e+08
3                       23468               7.717497e+07
4                       21387               6.980101e+07

In [79]:
# Supprimer les colonnes où toutes les valeurs sont NaN
df_sans_nans_all = df.dropna(axis=1, how='all')

# Afficher le DataFrame après suppression des colonnes où toutes les valeurs sont NaN
print(df_sans_nans_all.head())

  Numéro                      Nom  Année de revenus  Nombre de foyers fiscaux  \
0    010                      Ain              1984                    181534
1    020                    Aisne              1984                    235174
2    030                   Allier              1984                    173330
3    040  Alpes-de-Haute-Provence              1984                     55860
4    050             Hautes-Alpes              1984                     49883

   Revenus nets imposables     Impôt net  Nombre de foyers fiscaux.1  \
0             1.737362e+09  1.932327e+08                      113754
1             2.077326e+09  2.257485e+08                      134875
2             1.432056e+09  1.464150e+08                       95784
3             4.936463e+08  5.418975e+07                       32392
4             4.335536e+08  4.762610e+07                       28496

   Revenus nets imposables.1  Nombre de foyers fiscaux.2  \
0               1.475392e+09                       67780
1               1.703993e+09                      100299
2               1.171677e+09                       77546
3               4.164714e+08                       23468
4               3.637526e+08                       21387

   Revenus nets imposables.2
0               2.619703e+08
1               3.733335e+08
2               2.603782e+08
3               7.717497e+07
4               6.980101e+07

In [80]:
# Liste des noms de villes à conserver
villes_a_garder = ['Bouches-du-Rhône', 'Charente', 'Manche', 'Pas-de-Calais', 'Pyrénées-Atlantiques', 'Haute-Savoie', 'Vienne', "Val-D'OIS"]

# Filtrer le DataFrame pour ne conserver que les lignes où la colonne "Nom" contient les villes spécifiées
df_filtre = df[df['Nom'].isin(villes_a_garder)]

# Afficher le DataFrame filtré
print(df_filtre)

      Unnamed: 0 Numéro                   Nom  Année de revenus  \
12           NaN    130      Bouches-du-Rhône              1984
15           NaN    160              Charente              1984
50           NaN    500                Manche              1984
62           NaN    620         Pas-de-Calais              1984
64           NaN    640  Pyrénées-Atlantiques              1984
...          ...    ...                   ...               ...
1150         NaN    500                Manche              1995
1162         NaN    620         Pas-de-Calais              1995
1164         NaN    640  Pyrénées-Atlantiques              1995
1174         NaN    740          Haute-Savoie              1995
1186         NaN    860                Vienne              1995

      Nombre de foyers fiscaux  Revenus nets imposables     Impôt net  \
12                      748910             7.270905e+09  9.042048e+08
15                      150660             1.295204e+09  1.358979e+08
50                      201625             1.676938e+09  1.672631e+08
62                      611970             5.029460e+09  4.704323e+08
64                      258853             2.293550e+09  2.589245e+08
...                        ...                      ...           ...
1150                    245958             2.824784e+09  2.250045e+08
1162                    699318             7.795596e+09  6.044970e+08
1164                    316817             3.885749e+09  3.597412e+08
1174                    308127             4.014038e+09  4.169908e+08
1186                    200280             2.435372e+09  2.168745e+08

      Nombre de foyers fiscaux.1  Revenus nets imposables.1  \
12                        464091               6.288151e+09
15                         83551               1.065293e+09
50                        106977               1.337983e+09
62                        321224               3.900604e+09
64                        147433               1.919325e+09
...                          ...                        ...
1150                      105276               2.027761e+09
1162                      279106               5.385767e+09
1164                      147918               2.983955e+09
1174                      163733               3.275868e+09
1186                       92008               1.853521e+09

      Nombre de foyers fiscaux.2  Revenus nets imposables.2
12                        284819               9.827537e+08
15                         67109               2.299112e+08
50                         94648               3.389557e+08
62                        290746               1.128856e+09
64                        111420               3.742254e+08
...                          ...                        ...
1150                      140682               7.970224e+08
1162                      420212               2.409830e+09
1164                      168899               9.017940e+08
1174                      144394               7.381693e+08
1186                      108272               5.818514e+08

[84 rows x 11 columns]

In [82]:
# Enregistrer le DataFrame filtré dans un fichier Excel
df_filtre.to_excel('C:/Users/ketre/Desktop/Projet-Power BI/classeur_filtre.xlsx', index=False)

In [39]:
import pandas as pd

# Charger la feuille 2000_2017 du classeur impots

feuille = '2000_2017'
df = pd.read_excel('C:/Users/ketre/Desktop/Projet-Power BI/impots.xlsx', sheet_name=feuille, header=7)

# Afficher les premières lignes du DataFrame pour vérifier le chargement
print(df.head())

   Unnamed: 0 Numéro                      Nom  Année de revenus  \
0         NaN    010                      AIN              2000
1         NaN    020                    AISNE              2000
2         NaN    030                   ALLIER              2000
3         NaN    040  ALPES-DE-HAUTE-PROVENCE              2000
4         NaN    050             HAUTES-ALPES              2000

   Nombre de foyers fiscaux  Revenu fiscal de référence    Impôt net  \
0                    270323                4.236568e+09  330708954.0
1                    281700                3.668949e+09  270868430.0
2                    200232                2.496687e+09  172820429.0
3                     79796                1.030000e+09   74015906.0
4                     70047                9.211483e+08   65079459.0

   Nombre de foyers fiscaux.1  Revenu fiscal de référence.1  \
0                      149843                  3.348763e+09
1                      129572                  2.727694e+09
2                       93826                  1.871594e+09
3                       38452                  7.882146e+08
4                       34570                  7.058072e+08

   Nombre de foyers concernés       Montant  Nombre de foyers concernés.1  \
0                      187071  4.082817e+09                         79670
1                      180915  3.240829e+09                         93013
2                      111923  1.956063e+09                         81433
3                       46827  8.058799e+08                         30267
4                       43434  7.443642e+08                         24691

      Montant.1
0  1.151695e+09
1  1.267252e+09
2  1.114974e+09
3  4.396727e+08
4  3.476320e+08

In [41]:
# Supprimer les colonnes où toutes les valeurs sont NaN
df_sans_nans_all = df.dropna(axis=1, how='all')

# Afficher le DataFrame après suppression des colonnes où toutes les valeurs sont NaN
print(df_sans_nans_all.head())

  Numéro                      Nom  Année de revenus  Nombre de foyers fiscaux  \
0    010                      AIN              2000                    270323
1    020                    AISNE              2000                    281700
2    030                   ALLIER              2000                    200232
3    040  ALPES-DE-HAUTE-PROVENCE              2000                     79796
4    050             HAUTES-ALPES              2000                     70047

   Revenu fiscal de référence    Impôt net  Nombre de foyers fiscaux.1  \
0                4.236568e+09  330708954.0                      149843
1                3.668949e+09  270868430.0                      129572
2                2.496687e+09  172820429.0                       93826
3                1.030000e+09   74015906.0                       38452
4                9.211483e+08   65079459.0                       34570

   Revenu fiscal de référence.1  Nombre de foyers concernés       Montant  \
0                  3.348763e+09                      187071  4.082817e+09
1                  2.727694e+09                      180915  3.240829e+09
2                  1.871594e+09                      111923  1.956063e+09
3                  7.882146e+08                       46827  8.058799e+08
4                  7.058072e+08                       43434  7.443642e+08

   Nombre de foyers concernés.1     Montant.1
0                         79670  1.151695e+09
1                         93013  1.267252e+09
2                         81433  1.114974e+09
3                         30267  4.396727e+08
4                         24691  3.476320e+08

In [43]:
# Liste des noms de villes à conserver
villes_a_garder = ['BOUCHES-DU-RHONE', 'CHARENTE', 'MANCHE', 'PAS-DE-CALAIS', 'PYRENEES-ATLANTIQUES', 'HAUTE-SAVOIE', 'VIENNE', "VAL-D'OISE"]

# Filtrer le DataFrame pour ne conserver que les lignes où la colonne "Nom" contient les villes spécifiées
df_filtre = df[df['Nom'].isin(villes_a_garder)]

# Afficher le DataFrame filtré
print(df_filtre)

    Unnamed: 0  Numéro                   Nom  Année de revenus  \
0          NaN     130      BOUCHES-DU-RHONE              2019
1          NaN     160              CHARENTE              2019
2          NaN     500                MANCHE              2019
3          NaN     620         PAS-DE-CALAIS              2019
4          NaN     640  PYRENEES-ATLANTIQUES              2019
5          NaN     740          HAUTE-SAVOIE              2019
6          NaN     860                VIENNE              2019
7          NaN     950            VAL-D'OISE              2019
8          NaN     130      BOUCHES-DU-RHONE              2020
9          NaN     160              CHARENTE              2020
10         NaN     500                MANCHE              2020
11         NaN     620         PAS-DE-CALAIS              2020
12         NaN     640  PYRENEES-ATLANTIQUES              2020
13         NaN     740          HAUTE-SAVOIE              2020
14         NaN     860                VIENNE              2020
15         NaN     950            VAL-D'OISE              2020

    Nombre de foyers fiscaux  Revenu fiscal de référence   Impôt net  \
0                    1229376                3.270015e+10  2424380835
1                     212412                5.021583e+09   253492378
2                     291107                7.289796e+09   344459940
3                     821435                1.854209e+10   878714273
4                     414238                1.115047e+10   667416218
5                     476543                1.752076e+10  1001391556
6                     247588                6.012725e+09   298684336
7                     696939                1.964260e+10  1416414239
8                    1245999                3.355050e+10  2359547882
9                     214891                5.166990e+09   248455227
10                    295376                7.443278e+09   328258225
11                    832358                1.898358e+10   850567053
12                    421457                1.153353e+10   661299747
13                    487221                1.801668e+10   967230147
14                    250537                6.137161e+09   283997044
15                    708188                1.999747e+10  1357074583

    Nombre de foyers fiscaux.1  Revenu fiscal de référence.1  \
0                       600045                  2.513993e+10
1                        98126                  3.506238e+09
2                       140959                  5.080436e+09
3                       331867                  1.210259e+10
4                       209851                  8.285258e+09
5                       271291                  1.265459e+10
6                       120008                  4.291444e+09
7                       361644                  1.527690e+10
8                       554954                  2.501140e+10
9                        87425                  3.441209e+09
10                      125914                  4.920435e+09
11                      305094                  1.195311e+10
12                      189597                  8.212360e+09
13                      244999                  1.204322e+10
14                      105527                  4.125368e+09
15                      343036                  1.515431e+10

    Nombre de foyers concernés       Montant  Nombre de foyers concernés.1  \
0                       772449  2.230289e+10                        417182
1                       123257  3.109848e+09                         88395
2                       170713  4.487518e+09                        126494
3                       506948  1.288313e+10                        300129
4                       249421  6.856314e+09                        165652
5                       337669  1.379591e+10                        141705
6                       151416  3.962325e+09                         95261
7                       501621  1.575011e+10                        176512
8                       782683  2.278684e+10                        419308
9                       124506  3.174316e+09                         88675
10                      172858  4.596213e+09                        127283
11                      512837  1.310587e+10                        300659
12                      253868  7.045457e+09                        167280
13                      345072  1.419354e+10                        143437
14                      152949  4.023206e+09                         95629
15                      505945  1.599702e+10                        176712

       Montant.1
0   9.530159e+09
1   1.925000e+09
2   2.798147e+09
3   6.253867e+09
4   3.975040e+09
5   3.601262e+09
6   2.157723e+09
7   4.508266e+09
8   9.710948e+09
9   1.969213e+09
10  2.882027e+09
11  6.409963e+09
12  4.102600e+09
13  3.728188e+09
14  2.214086e+09
15  4.565668e+09

In [42]:
import pandas as pd

# Charger la feuille 1984_1999 du classeur impots

feuille = '2019_2020'
df = pd.read_excel('C:/Users/ketre/Desktop/Projet-Power BI/impots.xlsx', sheet_name=feuille, header=7)

# Afficher les premières lignes du DataFrame pour vérifier le chargement
print(df.head())

   Unnamed: 0  Numéro                   Nom  Année de revenus  \
0         NaN     130      BOUCHES-DU-RHONE              2019
1         NaN     160              CHARENTE              2019
2         NaN     500                MANCHE              2019
3         NaN     620         PAS-DE-CALAIS              2019
4         NaN     640  PYRENEES-ATLANTIQUES              2019

   Nombre de foyers fiscaux  Revenu fiscal de référence   Impôt net  \
0                   1229376                3.270015e+10  2424380835
1                    212412                5.021583e+09   253492378
2                    291107                7.289796e+09   344459940
3                    821435                1.854209e+10   878714273
4                    414238                1.115047e+10   667416218

   Nombre de foyers fiscaux.1  Revenu fiscal de référence.1  \
0                      600045                  2.513993e+10
1                       98126                  3.506238e+09
2                      140959                  5.080436e+09
3                      331867                  1.210259e+10
4                      209851                  8.285258e+09

   Nombre de foyers concernés       Montant  Nombre de foyers concernés.1  \
0                      772449  2.230289e+10                        417182
1                      123257  3.109848e+09                         88395
2                      170713  4.487518e+09                        126494
3                      506948  1.288313e+10                        300129
4                      249421  6.856314e+09                        165652

      Montant.1
0  9.530159e+09
1  1.925000e+09
2  2.798147e+09
3  6.253867e+09
4  3.975040e+09

In [31]:
# Supprimer les colonnes où toutes les valeurs sont NaN
df_sans_nans_all = df.dropna(axis=1, how='all')

# Afficher le DataFrame après suppression des colonnes où toutes les valeurs sont NaN
print(df_sans_nans_all.head())

  Numéro           Nom  Année de revenus  Nombre de foyers fiscaux  \
0    2A0  CORSE-DU-SUD              2019                     93173
1    2B0   HAUTE-CORSE              2019                    103027
2    010           AIN              2019                    356616
3    020         AISNE              2019                    302651
4    030        ALLIER              2019                    205611

   Revenu fiscal de référence    Impôt net  Nombre de foyers fiscaux.1  \
0                2.444518e+09  175585710.0                       46601
1                2.374887e+09  146859667.0                       45952
2                1.113785e+10  635468433.0                      190099
3                6.820737e+09  333997423.0                      126460
4                4.637818e+09  214602764.0                       97123

   Revenu fiscal de référence.1  Nombre de foyers concernés       Montant  \
0                  1.849075e+09                       57801  1.551150e+09
1                  1.688052e+09                       60202  1.489545e+09
2                  8.077177e+09                      242270  8.525105e+09
3                  4.535409e+09                      184610  4.519237e+09
4                  3.219410e+09                      111009  2.701112e+09

   Nombre de foyers concernés.1     Montant.1
0                         35037  7.494819e+08
1                         40222  7.925709e+08
2                        119726  2.951435e+09
3                        112792  2.423991e+09
4                         93059  2.002232e+09